MemoryMingle/FE

src/layout/header/GroupPageHeader.js
src/pages/group/GroupMain.jsx
src/pages/group/GroupWrite.jsx

feat: groupmain datamap돌리기

---

src/App.jsx
src/index.css
src/layout/Layout.js
src/pages/app-introduction/Introduction.jsx

fix: 스타일 부분 수정

---

src/components/common/input/Input.jsx

borderColor 추가 및 font 수정
borderColor 추가 및 font 수정

fix: borderColor 추가 및 font 수정

---

src/components/common/input/Input.jsx

design: InputStyle 수정

---

src/components/common/input/Input.jsx

bodercolor 소문자로 수정
bodercolor 소문자로 수정

fix: bodercolor 소문자로 수정

---

src/pages/mypage/MyPage.jsx

eslint 오류 수정 - 파일 확장자명 추가
eslint 오류 수정 - 파일 확장자명 추가

fix: eslint 오류 수정 - 파일 확장자명 추가

---

src/hooks/upload.js
src/layout/footer/Footer.jsx
src/pages/group/GroupMain.jsx
src/pages/group/GroupWrite.jsx

Feat: Image Upload hooks 부분 .env파일 변수 이름 수정

 Feat: Image Upload hooks 부분 .env파일 변수 이름 수정

---

src/hooks/upload.js
src/layout/footer/Footer.jsx
src/pages/post/PostMain.jsx
src/pages/post/PostWrite.jsx
src/router/Router.jsx

feat: postwrite 파일 구현 

---

src/components/SignupModal.jsx
src/components/common/input/Input.jsx
src/hooks/upload.js
src/layout/header/SignupPageHeader.js
src/pages/signup-login/KakaoLogin.jsx
src/pages/signup-login/KakaoLoginRedirect.jsx
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserInfo.jsx
src/router/Router.jsx

회원가입완료 모달창 수정 및 카카오톡 소셜 로그인 기능 구현
회원가입완료 모달창 수정 및 카카오톡 소셜 로그인 기능 구현

feat: 회원가입완료 모달창 수정 및 카카오톡 소셜 로그인 기능 구현

---

src/pages/group/GroupMain.jsx
src/pages/group/GroupWrite.jsx

Feat: 날짜 보여지는 부분 수정 
####작업사항
Feat: 날짜 보여지는 부분 수정

Feat: 날짜 보여지는 부분 수정 

---

src/pages/signup-login/Signup.jsx

사용 가능한 아이디일 때 컬러 변경
회원가입페이지에서 사용 가능한 아이디일 때 컬러 변경

design: 사용 가능한 아이디일 때 컬러 변경

---

src/pages/signup-login/UserInfo.jsx

유저 프로필 페이지 업로드한 이미지가 노출되도록 수정
유저 프로필 페이지 업로드한 이미지가 노출되도록 수정
이미지 화면에 맞게 리사이징

fix: 유저 프로필 페이지 업로드한 이미지가 노출되도록 수정

---

src/index.css
src/layout/footer/Footer.js
src/layout/index.js
src/pages/app-introduction/Introduction.jsx
src/pages/group/GroupMain.jsx

Feat: 천체적인 CSS 수정중 

---

src/api/auth.js
src/pages/kakao-login/KakaoLoginRedirect.jsx
src/router/Router.jsx

카카오 소셜 로그인 구현 완료 및 유저 프로필 이미지 업로드 로직에서 키값 수정
카카오 소셜 로그인 구현 완료 및 유저 프로필 이미지 업로드 로직에서 키값 수정

카카오 소셜 로그인 구현 완료 및 유저 프로필 이미지 업로드 로직에서 키값 수정

---

src/components/common/input/Input.jsx
src/pages/kakao-login/KakaoLogin.jsx
src/pages/mypage/MyPage.jsx
src/pages/mypage/PasswordChange.jsx
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserInfo.jsx
src/router/Router.jsx

비밀번호 변경 페이지 구현 및 CSS 수정
- 비밀번호 변경 페이지 화면 구현
- 라우터 경로 추가
- Input 공통 컴포넌트 width 수정
- 회원가입/로그인/마이페이지 전체적인 CSS 수정

feat: 비밀번호 변경 페이지 구현 및 CSS 수정

---

package.json
src/App.jsx
src/api/groupMainApi.js
src/pages/group/GroupMain.jsx
yarn.lock

개요: 
reactQuery 세팅
작업사항:
reactQuery 세팅
Groupmain 에서 그룹데이터 가져올때 사용

feat: reactQuery 세팅

---

src/components/common/modal/SignupModal.jsx
src/hooks/userProfileUpload.js
src/pages/mypage/MyPage.jsx
src/pages/mypage/PasswordChange.jsx
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserInfo.jsx

회원가입/로그인/마이페이지 리팩토링
- 마이페이지 아이디, 로그아웃 버튼 추가
- 회원가입 완료 모달창 문구 변경
- 닉네임 체크, 프로필 이미지 업로드 함수 별도 파일로 분리
- 버튼 컴포넌트 사용하도록 수정

feat: 회원가입/로그인/마이페이지 리팩토링

---

src/api/auth.js
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Login.jsx
src/router/ProtectedRoute.jsx
src/router/Router.jsx

Protected Route 설정 및 로그아웃 기능 구현
- Protected Route 설정
- 로그아웃 기능 구현(테스트중)

feat: Protected Route 설정 및 로그아웃 기능 구현

---

src/pages/group/GroupMain.jsx

Feat: 그룹 수정 페이지 구현
Feat: 그룹 수정 페이지 구현

Feat: 그룹 수정 페이지 구현

---

src/layout/header/GroupPageHeader.js
src/pages/group/GroupMain.jsx

###개요
fix: groupmain footer 고정하는것

fix: groupmain footer 고정하는것

---

src/api/auth.js
src/pages/mypage/MyPage.jsx

마이페이지 내 프로필이미지, 닉네임 따로 변경하도록 수정
마이페이지 내 프로필이미지, 닉네임 따로 변경하도록 수정

마이페이지 내 프로필이미지, 닉네임 따로 변경하도록 수정

---

src/components/common/button/PlusButton.jsx
src/pages/group/GroupMain.jsx

feat: groupMain 플러스버튼 컴포넌트화
feat: groupMain 플러스버튼 컴포넌트화

feat: groupMain 플러스버튼 컴포넌트화

---

public/index.html
src/components/common/modal/DatePicker.jsx
src/components/common/modal/NicknameModal.jsx
src/pages/group/GroupEdit.jsx
src/pages/group/GroupWrite.jsx
src/pages/group/styleContainer.js
src/router/Router.jsx

feat: DatePicker 모달 구현
- 그룹추가하기페이지에서 DatePicker 모달 구현

feat: DatePicker 모달 구현

---

src/components/common/modal/ProfileModal.jsx
src/index.css

feat: profileModal 페이지 UI 변경

---

src/components/common/modal/MyPageProfileModal.jsx

마이페이지 모달창 수정
- 마이페이지 모달창 버튼 max-width 추가
- 콘솔 오류 수정

fix: 마이페이지 모달창 수정

---

src/api/auth.js
src/components/common/modal/MyPageProfileModal.jsx
src/pages/mypage/MyPage.jsx

프로필 이미지 삭제 구현 및 로그아웃 오류 수정
- 프로필 이미지 삭제 구현
- 로그아웃 오류 수정

feat: 프로필 이미지 삭제 구현 및 로그아웃 오류 수정

---

src/api/auth.js
src/components/common/header/Header.jsx
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserProfile.jsx
src/recoil/Atom.js
src/router/NotProtectedRoute.jsx
src/router/Router.jsx
src/utils/passwordValidation.js

회원탈퇴/자동 로그인 구현 및 라우터 설정
- 회원탈퇴 구현(디자인 추후 적용 예정)
- 자동 로그인 구현
- 로그인한 유저는 로그인페이지에 접근 못하도록 라우터 설정

feat: 회원탈퇴/자동 로그인 구현 및 라우터 설정

---

src/api/groupMainApi.js
src/components/common/modal/DatePicker.jsx
src/components/common/modal/MoreModal.jsx
src/components/common/modal/NicknameModal.jsx
src/pages/group/GroupEdit.jsx
src/pages/group/GroupMain.jsx
src/pages/group/GroupWrite.jsx
src/pages/group/styleContainer.js
src/pages/search/Search.jsx

feat: 그룹나가기기능 구현
- 그룹나가기기능 구현
- 수정하기 모달창

feat: 그룹나가기기능 구현

---

package.json
src/api/groupMainApi.js
src/pages/kakao-login/KakaoLoginRedirect.jsx
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserProfile.jsx
src/router/NotProtectedRoute.jsx
src/router/ProtectedRoute.jsx
src/router/Router.jsx
yarn.lock

React Secure Storage 사용하여 로컬스토리지에 userId 저장
- onMouseDown 이벤트 추가
- React Secure Storage 사용하여 로컬스토리지에 userId 저장

feat: React Secure Storage 사용하여 로컬스토리지에 userId 저장

---

src/components/common/modal/MoreModal.jsx
src/pages/search/Search.jsx

feat: searchPage 구현
- searchPage 구현

feat: searchPage 구현

---

src/components/common/avatar/Avatar.jsx
src/components/common/comment/Comment.jsx
src/components/common/modal/ProfileModal.jsx
src/pages/post/PostDetail.jsx
src/pages/post/PostMain.jsx
src/pages/post/PostWrite.jsx

DetailPage 댓글 기능 구현
댓글 기능 구현, Avatar 컴포넌트화, comment 컴포넌트 구현.

feat: 댓글 기능 구현

---

src/components/common/header/Header.jsx
src/pages/mypage/MyPage.jsx
src/pages/mypage/PasswordChange.jsx
src/pages/signup-login/Signup.jsx

닉네임 입력 input dynamic width 적용, 자동 제출되도록 수정
- 공통 헤더 CSS 수정
- 닉네임 입력 input dynamic width 적용
- 닉네임 입력 체크 버튼 제거, 엔터 치면 자동으로 제출되도록 수정

feat: 닉네임 입력 input dynamic width 적용, 자동 제출되도록 수정

---

src/pages/kakao-login/KakaoLoginRedirect.jsx

test: 카카오 로그인 테스트

---

src/layout/footer/Footer.js
src/pages/notice/Notice.jsx
src/router/Router.jsx

feat: 알림 기능 작업중

---

src/components/common/avatar/Avatar.jsx
src/components/common/comment/Comment.jsx
src/pages/post/PostDetail.jsx
src/pages/post/PostMain.jsx

삭제 기능 구현
Detail 페이지에서 댓들 기능 중 삭제 기능 구현

feat: 삭제 기능 구현

---

src/api/groupMainApi.js
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx

storage에 저장된 userId가 객체로 불러와지는 문제 수정

fix: storage에 저장된 userId가 객체로 불러와지는 문제 수정

---

src/index.css

fix: background image 수정

---

package.json
src/api/groupMainApi.js
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Login.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserProfile.jsx
yarn.lock

fix: react-secure-storage 제거

---

src/components/common/loading/LoadingSpinner.css
src/layout/footer/Footer.js
src/pages/kakao-login/KakaoLogin.jsx
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Login.jsx

fix: 알림 기능 얼럿창 띄우기 및 CSS 수정

---

src/components/common/loading/LoadingSpinner.jsx
src/pages/mypage/MyPage.jsx

mutation 사용하여 함수 리팩토링 및 props 제거

refactor: mutation 사용하여 함수 리팩토링 및 props 제거

---

src/components/common/loading/LoadingSpinner.css

fix: 로딩스피너 CSS 수정

---

src/pages/group/GroupEdit.jsx
src/pages/group/GroupMain.jsx
src/pages/group/GroupWrite.jsx
src/pages/group/styleContainer.js
src/pages/post/PostMain.jsx
src/pages/search/Search.jsx
src/recoil/Atom.js

개요
fix: loading spinner props 제거
작업사항
fix: loading spinner props 제거

fix: loading spinner props 제거

---

src/api/auth.js
src/components/common/modal/MemberOutModal.jsx
src/pages/mypage/MyPage.jsx

fix: 회원 탈퇴 로직 수정

---

package.json
src/components/common/iconComponent/IconComponents.jsx
src/components/common/modal/CropperModal.jsx
src/pages/kakao-login/KakaoLogin.jsx
src/pages/mypage/MyPage.jsx
yarn.lock

feat: 이미지 크롭 기능 구현

---

public/assets/svgs/close.svg
src/App.jsx
src/hooks/useToast.jsx
src/pages/mypage/MyPage.jsx
src/pages/mypage/PasswordChange.jsx

토스트 메시지 구현
- 토스트 메시지 구현
- 마이페이지, 비밀번호 변경 페이지 토스트 메시지 적용

feat: 토스트 메시지 구현

---

src/pages/app-introduction/Introduction.jsx

fix: 시작페이지 CSS 수정

---

src/components/common/modal/MoreModal.jsx
src/pages/group/GroupEdit.jsx
src/pages/group/styleContainer.js
yarn.lock

fix: onclose 제거 in moremodal

---

src/pages/mypage/MyPage.jsx
src/pages/mypage/PasswordChange.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserProfile.jsx

토스트 메시지 노출 시간 수정
- 토스트 메시지 노출 시간 수정

fix: 토스트 메시지 노출 시간 수정

---

src/pages/search/SearchAlbum.jsx

fix: 앨범검색페이지 닉네임 

---

src/pages/mypage/MyPage.jsx

fix: 로컬스토리지 groupName 제거

---

src/api/auth.js
src/api/profileImageUpload.js
src/pages/mypage/MyPage.jsx
src/pages/signup-login/Signup.jsx
src/pages/signup-login/UserProfile.jsx

아이디 중복 확인 검사 debounce 적용 및 이미지 전송 방식 변경
- 아이디 중복 확인 검사 debounce 적용
- 이미지 전송 방식 변경

아이디 중복 확인 검사 debounce 적용 및 이미지 전송 방식 변경

---

src/components/common/modal/CommonModal.jsx
src/components/common/modal/SignupModal.jsx
src/pages/app-introduction/Introduction.jsx

fix: 콘솔 에러 수정

---

src/pages/mypage/MyPage.jsx
src/pages/signup-login/Signup.jsx

콘솔 로그 및 주석 제거
- 콘솔 로그 제거
- 불필요한 주석 제거

fix: 콘솔 로그, 주석 제거

---

src/api/groupMainApi.js
src/api/searchApi.js
src/components/common/modal/MoreModal.jsx
src/pages/group/GroupEdit.jsx
src/pages/group/GroupWrite.jsx

fix: groupWrite/Edit 이미지 업로드
fix: groupWrite/Edit 이미지 업로드

fix: groupWrite/Edit 이미지 업로드

---

package.json
src/App.jsx
src/hooks/useSocketManager.jsx
src/index.js
src/layout/footer/Footer.js
src/pages/group/GroupMain.jsx
src/pages/notice/Notice.jsx
src/recoil/Atom.js
yarn.lock

알림 기능 구현(작업중)
- 알림 기능 구현(작업중)
- 로딩스피너 위치 수정
- 푸터 수정

feat: 알림 기능 구현(작업중)

---

src/api/noticeApi.js
src/hooks/useSocketManager.jsx
src/layout/footer/Footer.js
src/pages/notice/Notice.jsx

뱃지, 새로운 알림 지난 알림 구분 작업
- 새로운 알림 개수 뱃지 작업
- 새로운 알림 지난 알림 구분 작업

feat: 뱃지, 새로운 알림 지난 알림 구분 작업

---

src/api/noticeApi.js
src/hooks/useSocketManager.jsx
src/pages/notice/Notice.jsx

feat: 새로운 알림 목록에 바로 렌더링되도록 작업

---

src/hooks/useSocketManager.jsx
src/layout/footer/Footer.js
src/pages/notice/Notice.jsx

feat: 새로운 알림 뱃지에 카운트되도록 작업

---

src/hooks/useSocketManager.jsx
src/layout/footer/Footer.js
src/pages/notice/Notice.jsx
src/recoil/Atom.js

fix: 알림 상태 업데이트 리코일로 변경

---

src/components/common/modal/MoreModal.jsx

feat: 앨범에서 나간 경우 관련 알림 삭제되도록 구현

---

README.md
src/components/common/modal/MoreModal.jsx
src/hooks/useSocketManager.jsx

변수명 알림 메시지 수정 및 리드미 수정
- 변수명 수정
- 알림 메시지 수정
- 리드미 수정

fix: 변수명 알림 메시지 수정 및 리드미 수정
